[package]
name = "snapshot_fs"
version = "0.1.0"
authors = ["Tomasz Kłak <tomasz@tomaszklak.pl>"]

[dependencies]
fuse_mt = "0.3"
zip = "0.2"
libc = "0.2"
log = "0.3"
env_logger = "0.4"
time = "0.1"
flate2 = "0.2"
